version: "3.9"

services:
  ocr:
    build: .
    container_name: ocr-service
    ports:
      - "8000:8000"
    volumes:
      - ./app/storage/uploads:/app/app/storage/uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
